# brew bundle --file ~/work/repos/github.com/furu/dotfiles/Brewfile

brew 'envchain'
brew 'fish'
brew 'gmailctl'
brew 'libyaml'
brew 'lv'
brew 'watchman'
brew 'xcodes'

cask '1password'
cask 'aquaskk'
cask 'firefox'
cask 'font-hackgen-nerd'
cask 'ghostty'
cask 'google-chrome'
cask 'jetbrains-toolbox'
cask 'karabiner-elements'
cask 'logseq'
cask 'orbstack'
